#Base configuration
spring: 
  profiles:
    active: dev
---
spring: 
  profiles: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: IES_DEV
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: IES_DEV
---
spring: 
  profiles: qa
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: IES_QA
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: IES_QA