server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console