spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: IES_DEV
    password: IES_DEV
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update